name: C/C++ CI

on:
  push:
    branches: [ main, generator ]
  pull_request:
    branches: [ main ]

jobs: 
  test:
    
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --remote
    - name: make
      run: make
    - name: Run testsuite compile and interpret mode 
      run: cd ifj-testsuite && python2 testsuite.py -c ../src/main
    - name: Display test log
      run: cat ifj-testsuite/log
