name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
      
  test:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: Checkout submodules
      run: git submodule update --init
    - name: Install golang
      run: sudo apt install golang
    - name: Run tests
      run: cd ifj-testsuite && python2 testsuite.py -mc -c ../src/main
